version: "3.7"

services:
    deepstream:
        image: deepstreamio/deepstream.io:latest
        ports:
            - 6020:6020    

    client:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./dist/client:/usr/share/nginx/html:ro
            - ./nginx.debug.conf:/etc/nginx/conf.d/default.conf:ro
        
    server:
        image: goonsackgames-pvp:latest
        ports:
            - 6020:6020  
